### ISSUE TITLE
Date the feed list was last updated

### ISSUE THREAD

**Issue by smsm1** [smsm1/blogs.osm.org#2]
So that we have the correct last updated date for the OPML feed.
http://planet-osm.shaunmcdonald.me.uk/planet.opml.xml

https://github.com/smsm1/blogs.osm.org/blob/master/theme/opml.xml.erb

**Comment by smsm1** [comment]
Thanks, it seems I needed to use site.updated instead of last_update, which doesn't exist.

**Comment by geraldb** [comment]
Thanks for retrying. Sorry. Yes it's `site.updated` -- see  e.g. the [db tables/schema source](https://github.com/feedreader/pluto.models/blob/master/lib/pluto/schema.rb)

```
 t.datetime :updated   # date for subscription list last updated via pluto
```

Happy New Year. Prosit 2015. Cheers.
